---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- set_fact:
    kibana_etc: /opt/kibana/config
  when: kibana_repo_version == '4.x'
- set_fact:
    kibana_etc: /etc/kibana
  when: kibana_repo_version == '5.x'
- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_etc }}/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Ensure kibana log dir exists with right permissions
  file: dest={{ kibana_logging_dest | dirname }} state=directory
- name: Ensure kibana log dir has right permissions with acl
  acl: name={{ kibana_logging_dest | dirname }} entity=kibana etype=user permissions="rwx" state=present

